# Generated by Django 4.1.9 on 2023-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_userhistory_bid_remove_userhistory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
