# Generated by Django 4.1.9 on 2023-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201105_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Antiques', 'Antiques'), ('Clothes', 'Clothes'), ('Decoration', 'Decoration'), ('Electronics', 'Electronics'), ('Valuables', 'Valuables'), ('Other', 'Other')], default='Other', max_length=11),
        ),
    ]
