# Generated by Django 4.1.9 on 2023-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_description_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
