# Generated by Django 4.1.9 on 2023-07-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_watchlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='auction_end_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('ANTIQUES', 'Antiques'), ('CLOTHES', 'Clothes'), ('DECORATION', 'Decoration'), ('ELECTRONICS', 'Electronics'), ('VALUABLES', 'Valuables'), ('OTHER', 'Other')], default='Other', max_length=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='None/NIA.png', upload_to='listing_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
