# Generated by Django 4.1.9 on 2023-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_bid_id_alter_comment_id_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Closed', 'CLOSED')], default='Pending', max_length=10),
        ),
    ]
