# Generated by Django 4.1.9 on 2023-07-23 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
